"""role

Revision ID: f46bb74b9690
Revises: ba396c26fa59
Create Date: 2021-03-14 14:30:12.071713

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f46bb74b9690'
down_revision = 'ba396c26fa59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'roles',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=80), nullable=True),
        sa.Column('description', sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name')
    )
    op.create_table(
        'roles_users',
        sa.Column('user_id', sa.Integer(), nullable=True),
        sa.Column('role_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    op.add_column('users', sa.Column('active', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('updated_on', sa.DateTime(), nullable=True))
    op.alter_column('users', 'email', existing_type=sa.VARCHAR(length=100), nullable=True)
    op.alter_column('users', 'username', existing_type=sa.VARCHAR(length=50), nullable=True)
    op.create_unique_constraint(None, 'users', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.alter_column(
        'users',
        'username',
        existing_type=sa.VARCHAR(length=50),
        nullable=False
    )
    op.alter_column(
        'users',
        'email',
        existing_type=sa.VARCHAR(length=100),
        nullable=False
    )
    op.drop_column('users', 'updated_on')
    op.drop_column('users', 'name')
    op.drop_column('users', 'active')
    op.drop_table('roles_users')
    op.drop_table('roles')
    # ### end Alembic commands ###
